### ISSUE TITLE
Cannot convert from level 2 to level 3 using libSBML 

### ISSUE THREAD

**Issue by haleyyew** [NRNB-GSoC2017-SBML2SBGNML-Converters/SBML2SBGNML#36]
- I was trying to convert an SBML from level 2 to level 3 using libSBML. Here's the approach I used:  
- I downloaded the binary for libSBML on https://sourceforge.net/projects/sbml/files/libsbml/5.15.0/stable/Windows/ and installed it.  
- I ran `sbfConverterGUI.bat` but couldn't find the SBML2SBML_L3V1 from the list.  
- I included `CLASSPATH=C:\...\libsbmlj.jar` to environment variables  
- Still couldn't find the converter.  
- I added C:\...\libsbmlj.jar to Java Build Path  
- In command prompt, I ran: `Converter.java SBMLModel SBML2SBML_L3V1 C:\...\examples\Complete_Example_level2.xml`
- I get a `java.lang.ClassNotFoundException: org.sbfc.converter.SBML2SBML` exception.  
- In Eclipse, I tried to run the `main()` method in `Converter.java` but still get the same error.  
- I know that the SBML2SBML converter is using `libsbml-5.11.4.jar`. Replacing `libsbml-5.11.4.jar` with `libsbmlj.jar` didn't help.  I downloaded `libsbmlj.jar` from the libSBML website.
- I'm still using the old project code, not the updated one 
- What is miriam.xml used for? Does it help to modify it?

**Comment by niko-rodrigue** [comment]
You should convert your project, better to start to use it as soon as possible but may be we can look at that during the meeting.
What I have notice is that may be on windows 10, you have to copy the libsbml dll at the root of the project so that they are detected.

**Comment by niko-rodrigue** [comment]
Definitively try again on the new project structure. you have to be sure that there is only one version of the libsbml jar file in your classpath and that it correspond to the libsbml version that you installed.

**Comment by haleyyew** [comment]
Here's what I did using `org.sbml.libsbml`:
1. After installing `libSBML-5.15.0`, I added `bindings/java/sbmlj.dll` to my `java.library.path` by adding `bindings/java/` to the `PATH` environment variable. I also added the `libsbmlj.jar` to my Build Path.
2. Then I created a `main()` method in `org.sbfc.converter.sbml2sbml.SBML2SBML` like the following: 
```
	public static void main(String[] args) throws ReadModelException, ConversionException {
		
		GeneralModel inputModel = new SBMLModel();
		GeneralConverter converter = new SBML2SBML();
		Map<String, String> options = new HashMap<String, String>();
		
		inputModel.setModelFromFile("C:/Users/HY/Documents/SBML2SBGN/sbfc_new/examples/Complete_Example_level2.xml");
		options.put("sbml.target.level", "3");
		options.put("sbml.target.version", "1");
		converter.setOptions(options);
		converter.convert(converter.getInputModel());
	}
```
3. However, I still get the following error:
```
Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: java.lang.RuntimeException: You need to install libsbml before being able to use the SBML2SBML converter.
```
4. So I tried to load the `sbmlj` library by hard coding its location:
```
//System.loadLibrary("sbmlj");
System.load("C:/Program Files/SBML/libSBML-5.15.0-libxml2-x64/bindings/java/sbmlj.dll");  
```
5. This time, I'm getting a different error:
```
WARN  org.sbml.jsbml.xml.parsers.XMLNodeReader - The type of String 'annotation' on the element listOfLayouts (ListOf) is unknown! Some data might be lost.
```
6. This error is consistent with the fact that libSBML cannot convert SBML with layout.

**Comment by haleyyew** [comment]
I guess I'm going to skip converting all the SBML level 2 examples for now.

**Comment by niko-rodrigue** [comment]
I think, that's already a good start as you were able to use libsbml from java. At least, if we really need to use it at some point, you are already setup. But I agree with you that converting the L2 form is not a priority, we want the converters to work with L3 in the first place.

As for libSBML not able to convert the layout, we have seen last week with Sarah that we need to use an other converter, not the default one, so I will try to produce the code for tomorrow and explain as well how to use it in your eclipse project without having to create a main method inside the converter class your want to use.
